return {
  -- {
  --   'obsidian-nvim/obsidian.nvim',
  --   version = '*', -- recommended, use latest release instead of latest commit
  --   lazy = true,
  --   ft = 'markdown',
  --   dependencies = {
  --     -- Required.
  --     'nvim-lua/plenary.nvim',
  --   },
  --   config = function()
  --     require('obsidian').setup {
  --       footer = {
  --         enabled = false,
  --       },
  --       legacy_commands = false,
  --       ui = { enable = false },
  --       workspaces = {
  --         {
  --           name = 'personal',
  --           path = '~/Documents/notes',
  --         },
  --         {
  --           name = 'notes',
  --           path = '~/notes',
  --         },
  --       },
  --       picker = {
  --         name = 'snacks.pick',
  --       },
  --       completion = {
  --         nvim_cmp = false,
  --         blink = true,
  --       },
  --     }
  --   end,
  -- },
}
